config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  devise_for :users
  get 'home/about' =>'homes#about', as: 'about'
  resources :users, only: [:edit, :index, :show, :update]
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length:{maximum:200}



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

has_one_attached :profile_image

def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end
  validates :name, uniqueness: true
  validates :name, length:{minimum: 2,maximum:20}
  validates :introduction, length:{maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
  user_path(current_user)
 end

 def after_sign_out_path_for(resource)
  root_path
 end

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
 end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Signed in successfully."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
     params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
  @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    @book = Book.new
    render :edit
    end
  end

  private

  def user_params
     params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
        <h2>User info</h2>
        <%= image_tag user.get_profile_image(100, 100) %>
        <table class="table">
            <tr>
            <th>name</th>
            <th><%= user.name %></th>
            </tr>
            <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
            </tr>
        </table>

        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>

        <h2>New book</h2>

        <%= form_with model: book do |f| %>
        <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class:'form-control book_title' %>
        </div>

        <div class="form-group">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, class:'form-control book_title' %>
        </div>

        <div class="form-group">
        <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
        <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>Editing Book</h2>


  <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_with model: @book do |f| %>

  <div>Title</div>
  <%= f.text_field :title %>

  <div>本文</div>
  <%= f.text_area :body %><br>

  <%= f.submit 'Update Book', class:"btn btn-success" %></br>

  <%= link_to 'Show', book_path(@book.id) %> |

  <%= link_to 'Back', books_path %>

  <% end %>


    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

      <%= render 'list', book: @book, user: current_user %>
      </div>

      <div class="col-md-8 offset-md-1">

      <h2>Books</h2>

      <table class="table">
      <tr>
        <th>Title</th>
        <th>Opinion</th>
        </tr>

  <% @books.each do |book| %>
  <tr>
    <td>
    <%= link_to user_path(book.user.id) do %>
    <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %>
    </td>
    <td>
    <%= link_to book.title, book_path(book.id) %>
    </td>
    <td>
    <%= book.body %>
    </td>
  </tr>
  <% end %>
  </table>


</div>
</div>

</div>









</main>

app/views/books/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
<%= render 'list', book: @books, user: @user %>
</div>

<div class="col-md-8 offset-md-1">
<h2>Book detail</h2>
<table class="table">
  <tr>
    <td>
    <%= link_to user_path @user do %>
    <%= image_tag @book.user.get_profile_image(100,100) %>
    <br>
    <%= @user.name %>
    </td>

    <td><%= @book.title %></td>
    <td><%= @book.body %></td>

    <% end %>
    <% if @book.user == current_user %>
    <td>
    <%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success" %>
    </td>
    <td>
    <%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削しますか？" %>
    <% end %>
    </td>

  </tr>

</table>

</div>
</div>
</div>

app/views/homes/about.html.erb
<main>

<div class="container">
  <div class="row">
  <h1 class="px-3 mx-auto">welcome to
  <i class="fas fa-book" aria-hidden="true"></i>
  <strong>Bookers</strong>!
  </h1>

</div>
</div>
</main>

app/views/homes/top.html.erb
<main>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to
    <i class="fas fa-book" aria-hidden="true"></i>
    <strong>Bookers</strong>!!</h1>

    <p>in
    <i class="fas fa-book" aria-hidden="true"></i>
    <strong>Bookers</strong>,</p>

    <p>you can share and exchange your opinions ,
    inpressions , and emotions</p>

    <p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign in" %>
      </div>
      <div class="row">
        <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign up" %>
      </div>
  </div>
    </div>
  </div>
</div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/57fefeb910.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


      <% if user_signed_in? %>

      <body>
    <header class="shadow-sm">
      <div class="container-fould">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="navbar-brand">
       <%= link_to "Bookers", root_path, class: "navbar-brand" %>
      </div>

        <ul class="ml-auto d-flex">
          <li class="nav-link text-light ">
            <%= link_to user_path(current_user), class: "nav-link text-light" do %>
            <i class="fas fa-home"></i>Home
            <% end %>
          </li>

          <li class="nav-link text-light ">
            <%= link_to users_path, class: "nav-link text-light" do  %>
            <i class="fas fa-users"></i>Users
            <% end %>

          <li class="nav-link text-light ">
            <%= link_to books_path, class: "nav-link text-light" do  %>
            <i class="fas fa-book-open"></i>Books
            <% end %>
          </li>

          <li class="nav-link text-light ">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>Log out
            <% end %>
          </li>
          </ul>
          </nav>

      <% else %>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="navbar-brand">
       <%= link_to "Bookers", root_path, class: "navbar-brand" %>
       </div>

        <ul class="ml-auto d-flex">
          <li class="nav-link text-light ">
            <%= link_to root_path, class: "nav-link text-light" do %>
            <i class="fas fa-home"></i>Home
            <% end %>
          </li>

          <li class="nav-link text-light ">
            <%= link_to about_path, class: "nav-link text-light" do %>
            <i class="fas fa-link"></i>About
            <% end %>
          </li>

          <li class="nav-link text-light ">
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
            <i class="fas fa-user-plus"></i>Sign up
            <% end %>
          </li>

          <li class="nav-link text-light ">
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
            <i class="fas fa-sign-in-alt"></i>Log in
            <% end %>
          </li>

      </ul>
      </nav>
      </div>
    </header>
      <% end %>
      <div>
      <%= flash[:notice] %>
      </div>
    <%= yield %>



  <footer>
    <div class="container mt-5">
      <div class="row">
      <div class="mx-auto">
        <p>CopyRight infratop.inc</p>
      </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/users/edit.html.erb
  <div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <h2>User info</h2>

  <% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>


  <%= form_with model: @user do |f| %>

  <div>name</div>
  <%= f.text_field :name %>

  <div>Image</div>
  <%= f.file_field :profile_image %>

  <div>Introdution</div>
  <%= f.text_area :introduction %><br>

  <%= f.submit 'Update User', class: "btn btn-secondary" %><br>

  <% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'books/list', book: @book, user: current_user %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
    <table class="table">
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
    <tr>
      <% @users.each do |user| %>
      <td>
        <%= image_tag user.get_profile_image(100,100) %>
      </td>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user_path(user.id) %></td>
    </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
      <%= render 'books/list', book: @book, user: @user %>
      </div>

      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table">
<tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
</tr>

  <% @books.each do |book| %>
  <tr>
    <td>

    <%= link_to user_path(@user.id) do %>
    <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %>
    </td>
    <td>
    <%= link_to book.title, book_path(book.id) %>
    </td>
    <td>
    <%= book.body %>
    </td>
  </tr>
  <% end %>
</table>

</div>
</div>

</div>